Repository paulaandrezza/examHub, pull requests merged in 2024-05, with the labels that each got.

#15 Update README.md
  README.md
Labels: documentation

#14 Create LICENSE
  LICENSE
Labels: documentation

#16 Feat/implement pacient interface
  LICENSE
  resources/sql/create_tables.sql
  resources/sql/insert_data.sql
  resources/sql/querys/paciente.sql
  src/Main.java
  src/controller/PacienteController.java
  src/model/entities/Pessoa.java
  src/model/persistence/dao/paciente/PacienteDAO.java
  src/model/persistence/dao/paciente/PacienteFullDTO.java
  src/model/persistence/dao/paciente/PessoaDTO.java
  src/view/gui/CadastroPanel.java
  src/view/gui/EnderecoPanel.java
  src/view/gui/PacientePanel.java
  src/view/gui/PessoaPanel.java
Labels: update

#20 feat: implement authentication
  src/Main.java
  src/controller/AuthController.java
  src/model/entities/Funcionario.java
  src/model/exceptions/EmailAndPasswordIncorrectException.java
  src/model/exceptions/EmailNotFoundException.java
  src/model/persistence/dao/auth/AuthDAO.java
  src/model/persistence/dao/auth/FuncionarioDTO.java
Labels: enhancement
